### ISSUE TITLE
Gold counter from right side, tower and others counters dont update in correct form

### ISSUE THREAD

**Issue by roobdesigns** [Dan-Shields/League-OCR-HUD#7]
![screenshot-411](https://github.com/Dan-Shields/League-OCR-HUD/assets/47200121/f8b9fe7b-c1c5-4389-9667-8cb4a957510d)

**Comment by Dan-Shields** [comment]
@roobdesigns looks like its picking up the "8" in the gold text reading "300|480"

@Fill30 do you have any idea if the gold text under the tower count is new since we last updated and/or is it toggleable?

**Comment by MathieuNeveu** [comment]
Hi ! 
I have the same kind of issues concerning the right team golds count and drake / nash timers so i commented this issue instead of creating a new one.
As i understood that's an ia model reading the hud to write into files. Looks like the HUD has been modified by Riot recently and in the right side the tower count seems to be very close to the gold count. It may cause that the actuel model is maybe 'outdated' ? 
I took some screenshots of these cases, note that these errors are intermittents but occurs more often when the gold count is > 9K. 

**Nash and Drake timers are not filled.** 
![HUD BUG 4](https://github.com/Dan-Shields/League-OCR-HUD/assets/23449532/45d5f3bc-4411-4ec8-89be-7ffc20cc7a3d)
**Gold count missing the tens** 
![BUG HUD 2](https://github.com/Dan-Shields/League-OCR-HUD/assets/23449532/a78fa520-e1a7-4303-a250-e451034b1ee1)
![BUG HUD 3](https://github.com/Dan-Shields/League-OCR-HUD/assets/23449532/ad8b162d-b47b-423b-9be6-706deefa3be5)
![BUG HUD 1](https://github.com/Dan-Shields/League-OCR-HUD/assets/23449532/19bd1057-b26d-4917-a63e-0e91fba1c227)

Have a good day !
